In [76]:
f = open('sentences.txt', 'r')
data_text = []
for line in f:
    data_text.append(line.strip())
f.close()

In [77]:
data_text

['In comparison to dogs, cats have not undergone major changes during the domestication process.',
 'As cat simply catenates streams of bytes, it can be also used to concatenate binary files, where it will just concatenate sequence of bytes.',
 'A common interactive use of cat for a single file is to output the content of a file to standard output.',
 'Cats can hear sounds too faint or too high in frequency for human ears, such as those made by mice and other small animals.',
 'In one, people deliberately tamed cats in a process of artificial selection, as they were useful predators of vermin.',
 'The domesticated cat and its closest wild ancestor are both diploid organisms that possess 38 chromosomes and roughly 20,000 genes.',
 'Domestic cats are similar in size to the other members of the genus Felis, typically weighing between 4 and 5 kg (8.8 and 11.0 lb).',
 'However, if the output is piped or redirected, cat is unnecessary.',
 'cat with one named file is safer where human error i

In [82]:
import re
data_text_split = []
for line in data_text:
    data_text_split.append(re.split('[^a-z]', line.lower()))

In [83]:
data_text_split

[['in',
  'comparison',
  'to',
  'dogs',
  '',
  'cats',
  'have',
  'not',
  'undergone',
  'major',
  'changes',
  'during',
  'the',
  'domestication',
  'process',
  ''],
 ['as',
  'cat',
  'simply',
  'catenates',
  'streams',
  'of',
  'bytes',
  '',
  'it',
  'can',
  'be',
  'also',
  'used',
  'to',
  'concatenate',
  'binary',
  'files',
  '',
  'where',
  'it',
  'will',
  'just',
  'concatenate',
  'sequence',
  'of',
  'bytes',
  ''],
 ['a',
  'common',
  'interactive',
  'use',
  'of',
  'cat',
  'for',
  'a',
  'single',
  'file',
  'is',
  'to',
  'output',
  'the',
  'content',
  'of',
  'a',
  'file',
  'to',
  'standard',
  'output',
  ''],
 ['cats',
  'can',
  'hear',
  'sounds',
  'too',
  'faint',
  'or',
  'too',
  'high',
  'in',
  'frequency',
  'for',
  'human',
  'ears',
  '',
  'such',
  'as',
  'those',
  'made',
  'by',
  'mice',
  'and',
  'other',
  'small',
  'animals',
  ''],
 ['in',
  'one',
  '',
  'people',
  'deliberately',
  'tamed',
  'cats',
  

In [84]:
clean_data = []
for sentence in data_text_split:
    for word in sentence:
        if word != '':
            clean_data.append(word) 

In [94]:
dict_data = {}
i = 0
for word in clean_data:
    if word in dict_data.keys():
        continue
    else:
        dict_data[word] = i
        i += 1

In [95]:
dict_data

{'in': 0,
 'comparison': 1,
 'to': 2,
 'dogs': 3,
 'cats': 4,
 'have': 5,
 'not': 6,
 'undergone': 7,
 'major': 8,
 'changes': 9,
 'during': 10,
 'the': 11,
 'domestication': 12,
 'process': 13,
 'as': 14,
 'cat': 15,
 'simply': 16,
 'catenates': 17,
 'streams': 18,
 'of': 19,
 'bytes': 20,
 'it': 21,
 'can': 22,
 'be': 23,
 'also': 24,
 'used': 25,
 'concatenate': 26,
 'binary': 27,
 'files': 28,
 'where': 29,
 'will': 30,
 'just': 31,
 'sequence': 32,
 'a': 33,
 'common': 34,
 'interactive': 35,
 'use': 36,
 'for': 37,
 'single': 38,
 'file': 39,
 'is': 40,
 'output': 41,
 'content': 42,
 'standard': 43,
 'hear': 44,
 'sounds': 45,
 'too': 46,
 'faint': 47,
 'or': 48,
 'high': 49,
 'frequency': 50,
 'human': 51,
 'ears': 52,
 'such': 53,
 'those': 54,
 'made': 55,
 'by': 56,
 'mice': 57,
 'and': 58,
 'other': 59,
 'small': 60,
 'animals': 61,
 'one': 62,
 'people': 63,
 'deliberately': 64,
 'tamed': 65,
 'artificial': 66,
 'selection': 67,
 'they': 68,
 'were': 69,
 'useful': 70,
 'p

In [107]:
import numpy as np
n = len(data_text)
d = len(dict_data)

matrix = np.zeros((n, d))

In [116]:
matrix

array([[1., 1., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 2., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 1., 1., 1.]])

In [108]:
matrix.shape

(22, 254)

In [109]:
from collections import Counter
i = 0
j = 0
for i in range(len(data_text_split)):
    for key in dict_data.keys():
        if key in data_text_split[i]:
            for word in data_text_split[i]:
                if word  == key:
                    j += 1
            matrix[i, dict_data.get(key)] += j
            j = 0

In [110]:
matrix

array([[1., 1., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 2., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 1., 1., 1.]])

In [114]:
from scipy.spatial import distance as ds

In [115]:
matrix[1]

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       1., 1., 2., 2., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [117]:
cosine = [] 
for line in matrix:
    cosine.append(ds.cosine(matrix[0], line))
    
cosine

[0.0,
 0.9527544408738466,
 0.8644738145642124,
 0.8951715163278082,
 0.7770887149698589,
 0.9402385695332803,
 0.7327387580875756,
 0.9258750683338899,
 0.8842724875284311,
 0.9055088817476932,
 0.8328165362273942,
 0.8804771390665607,
 0.8396432548525454,
 0.8703592552895671,
 0.8740118423302576,
 0.9442721787424647,
 0.8406361854220809,
 0.956644501523794,
 0.9442721787424647,
 0.8885443574849294,
 0.8427572744917122,
 0.8250364469440588]

ОТВЕТ 4 и 6