In [14]:
import sklearn.datasets as ds
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.model_selection import cross_val_score as cvs
from sklearn.naive_bayes import BernoulliNB, MultinomialNB, GaussianNB

X_digits, y_digits  = ds.load_digits(return_X_y=True)
X_breast_cancer, y_breast_cancer = ds.load_breast_cancer(return_X_y=True)

In [20]:
def write_answer_1(cvs_score, ans):
    with open(ans, "w") as fout:
        fout.write(str(cvs_score))
        
print(X_digits)
print(X_breast_cancer)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [22]:
BNB = BernoulliNB()
MNB = MultinomialNB()
GNB = GaussianNB()
result_digits = []

result_digits.append(cvs(BNB, X_digits, y_digits, cv=10, n_jobs=1).mean())
result_digits.append(cvs(MNB, X_digits, y_digits, cv=10, n_jobs=1).mean())
result_digits.append(cvs(GNB, X_digits, y_digits, cv=10, n_jobs=1).mean())

print(result_digits)
write_answer_1(max(result_digits), 'ans2.txt')

[0.8325170701427685, 0.8797858472998138, 0.8113904407200497]


In [23]:
BNB = BernoulliNB()
MNB = MultinomialNB()
GNB = GaussianNB()
result_breast_cancer = []

result_breast_cancer.append(cvs(BNB, X_breast_cancer, y_breast_cancer, cv=10, n_jobs=1).mean())
result_breast_cancer.append(cvs(MNB, X_breast_cancer, y_breast_cancer, cv=10, n_jobs=1).mean())
result_breast_cancer.append(cvs(GNB, X_breast_cancer, y_breast_cancer, cv=10, n_jobs=1).mean())

print(result_breast_cancer)
write_answer_1(max(result_breast_cancer), 'ans1.txt')

[0.6274122807017544, 0.8927944862155389, 0.9367794486215537]


In [24]:
write_answer_1('3 4', 'ans3.txt')